### ISSUE TITLE
dracut.sh should exit fatally if modules.dep is missing

### ISSUE THREAD

**Issue by jdconti** [haraldh/dracut#110]
If $no_kernel != yes, /proc/modules is populated, and $srcmods/modules.dep is missing I would expect dracut to exit fatally.  At present [it's only a warning.](https://github.com/haraldh/dracut/blob/60928f36b6c9a855077506444ea5edbe6be9ec4c/dracut.sh#L928)

**Comment by haraldh** [comment]
https://github.com/haraldh/dracut/commit/b019952f6df9b1dae54dd097f012e6c05fe6af00

**Comment by haraldh** [comment]
thanks!

**Comment by jdconti** [comment]
I had a diff ready for a PR but didn't want to send you a blind PR.  Thanks for the lightning fast update Harald!
