### ISSUE TITLE
Possible bug in initqueue.sh

### ISSUE THREAD

**Issue by ti-mo** [haraldh/dracut#31]
Hello!

I've stumbled across a small issue trying to boot RHEL7 from an iSCSI LUN. (Emulex adapter with firmware-configured targets) /proc/cmdline: `BOOT_IMAGE=/vmlinuz-3.10.0-123.el7.x86_64 root=UUID=**** ro iscsi_firmware rd.lvm.lv=rhel/root vconsole.keymap=us rd.lvm.lv=rhel/swap crashkernel=auto vconsole.font=latarcyrheb-sun16 ifname=**** rd.debug`

Note: Results are identical on the latest kernel. I know `iscsi_firmware` is deprecated, but this is what Anaconda still generates today, will report this some other time. They still appear to have the same functionality. Specifying `netroot=iscsi` and/or `rd.iscsi.firmware` has no effect.

In modules.d/99base/initqueue.sh:
```
44: [ -x "$exe" ] || exe=$(command -v $exe)
```
results in the following behaviour:
```
dracut-cmdline[265]: /usr/sbin/initqueue@37(): job=395
dracut-cmdline[265]: /usr/sbin/initqueue@43(): exe='/sbin/iscsiroot dummy '\''iscsi:'\'' '\''/sysroot'\'''
dracut-cmdline[265]: /usr/sbin/initqueue@44(): shift
dracut-cmdline[265]: /usr/sbin/initqueue@46(): '[' -x '/sbin/iscsiroot dummy '\''iscsi:'\'' '\''/sysroot'\''' ']'
dracut-cmdline[265]: //usr/sbin/initqueue@46(): command -v /sbin/iscsiroot dummy ''\''iscsi:'\''' ''\''/sysroot'\'''
dracut-cmdline[265]: /usr/sbin/initqueue@46(): exe=/sbin/iscsiroot
dracut-cmdline[265]: /usr/sbin/initqueue@49(): '[' -n yes ']'
dracut-cmdline[265]: /usr/sbin/initqueue@49(): echo '[ -e "$job" ] && rm -f -- "$job"'
dracut-cmdline[265]: /usr/sbin/initqueue@50(): '[' -n '' ']'
dracut-cmdline[265]: /usr/sbin/initqueue@51(): echo '/sbin/iscsiroot '
```

Bash does not deem `/sbin/iscsiroot dummy '\''iscsi:'\'' '\''/sysroot'\''` executable and uses `command` to get rid of the arguments.

`modules.d/95iscsi/iscsiroot.sh` doesn't appreciate this:
```
# Huh? Empty $1?
[ -z "$1" ] && exit 1

# Huh? Empty $2?
[ -z "$2" ] && exit 1
```

.. and never finishes the iscsi logins that are meant to follow.

As a workaround, I've simply commented out line 44 in initqueue.sh, as I honestly don't see the point in sanitizing input that has been generated by Dracut's own (trusted) scripts in the first place. If a user installs a hook that sends a malformed command line to the initqueue, that script needs to be fixed. It seems rather illogical to throw away the arguments to a command and execute it without them none the less. If anything, apparently this causes scripts to silently fail (which is something that should never happen anyway), which in turn causes headaches for the end user.

Commenting out line 44 works fine for me, but because of my very limited experience with this framework, it's rather difficult to judge whether or not this will break other functionality.

What do you think, @haraldh ?

Cheers!

Timo

**Comment by haraldh** [comment]
@ti-mo : will be soonish fixed in 7.1
