### ISSUE TITLE
Overlayfs as root filesystem

### ISSUE THREAD

**Issue by chrisnharvey** [haraldh/dracut#62]
Hi,

I'm currently building a distro for my personal needs which runs on my HDD from a live Fedora ISO. But I'd like to make the filesystem writeable using overlayfs. I'm using https://github.com/probonopd/SystemImageKit which is doing exactly what I want, except persisting data on the same partition.

So what I need to do is boot from the ISO on the HDD, this is working fine using SystemImageKit. I then need to use dracut to mount the root filesystem as an overlayfs of the live ISO's root filesystem and a directory on my HDD.

Essentially what I need to do is the following in the initramfs

```
mount --move / /os
mount <isodevice> /system
mount -t overlayfs -o lowerdir=/os,upperdir=/system/data overlayfs /
```

I'm just having trouble moving the root filesystem to another mount point. Then I can mount the HDD as read/write under /system then mount the root filesystem as an overlayfs of /os (original ISO root filesystem) and /system/data (a *real* directory on the HDD which sits alongside /boot).

In theory this should work if I can move the root filesystem.

I've tried this from the terminal my mounting the HDD under /mnt then running:
```
mount -t overlayfs -o lowerdir=/,upperdir=/mnt/data overlayfs /test
```

Then all my files are then stored in /mnt/data, and are merged with the root filesystem under the /test mount point, which is exactly what I need, but on the root filesystem.

I just need a way to get this same functionality working but under the root mount point instead of /test.

**Comment by haraldh** [comment]
you could remount /sysroot to /run/sysroot in the dracut mount hook and mount your stuff to /sysroot

 mkdir /run/sysroot; mount --move /sysroot /run/sysroot ... do stuff for /sysroot

**Comment by chrisnharvey** [comment]
Thanks @haraldh,

Just for the sake of clarity, I have added some other comments from our conversation on IRC.

Live system is mounted under /sysroot which can be moved to /run/sysroot

Live device is mounted in /run/initramfs/livedev
https://github.com/haraldh/dracut/blob/master/modules.d/90dmsquash-live/dmsquash-live-root.sh#L56

Then just run
```
mount -t overlayfs -o lowerdir=/run/sysroot,upperdir=/run/initramfs/<overlay directory> /sysroot
```

**Comment by probonopd** [comment]
> mkdir /run/sysroot; mount --move /sysroot /run/sysroot

That does not work:

```
mount: bad option. Note that moving a mount residing under a shared
mount is unsupported.
In some cases useful info is found in syslog - try
dmesg | tail or so.
```

**Comment by haraldh** [comment]
Maybe
mount --make-private /sysroot
or even
mount --make-rprivate /sysroot
before the mount --move
