### ISSUE TITLE
Errors in instmods_1 are ignored

### ISSUE THREAD

**Issue by devurandom** [haraldh/dracut#8]
Current behaviour:
When instmods_1 cannot find a module (for example), it returns an error (1). It's caller, instmods, aborts the installation of any further modules and returns also an error (1). dracut then ignores that error and does not even output a warning.

Expected behaviour:
Variant 1: instmods outputs a warning when instmods_1 returns an error, but continues to install the other modules.
Variant 2: dracut outputs an error message, including the module that failed, and aborts the whole operation.

**Comment by haraldh** [comment]
Should be fixed with current versions. Thanks!
