### ISSUE TITLE
Timed out waiting for device dev-mapper-live\x2drw.device.

### ISSUE THREAD

**Issue by cinquecento** [haraldh/dracut#82]
```
...
[  OK  ] Created slice system-checkisomd5.slice.
         Starting Media check on /dev/disk/by-label/Rawhide-Xfce-Live-715...
/dev/disk/by-label/Rawhide-Xfce-Live-715:   18335ea450d4b9e30c1ca5d4c56da09a
Fragment sums: c81ffdb6debc25cd97a6b74fcbdf7e498327361e86fde399e3cef839f91b
Fragment count: 20
Supported ISO: no
Press [Esc] to abort check.
Checking: 048.9% TIME ] Timed out waiting for device dev-mapper-live\x2drw.device.
[DEPEND] Dependency failed for /sysroot.
[DEPEND] Dependency failed for Initrd Root File System.
[DEPEND] Dependency failed for Reload Configuration from the Real Root.
Checking: 048.9%         Starting Emergency Shell...
[  OK  ] Reached target Initrd File Systems.
Checking: 048.9%[   92.060592] audit_printk_skb: 3 callbacks suppressed
Checking: 048.9[   92.081556] audit: type=1131 audit(1437065264.211:12): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=plymouth-start comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Checking: 048.9%Warning: /dev/mapper/live-rw does not exist
Checking: 049.0%
Checking: 049.0%Generating "/run/initramfs/rdsosreport.txt"
Checking: 049.4%

Entering emergency mode. Exit the shell to continue.
Type "journalctl" to view system logs.
You might want to save "/run/initramfs/rdsosreport.txt" to a USB stick or /boot
after mounting them and attach it to a bug report.


Checking: 100.0%

The media check is complete, the result is: PASS.

It is OK to use this media.
[  319.411745] audit: type=1130 audit(1437065491.564:13): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=checkisomd5@dev-disk-by\x2dlabel-Rawhide\x2dXfce\x2dLive\x2d715 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[  319.415191] audit: type=1131 audit(1437065491.568:14): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=checkisomd5@dev-disk-by\x2dlabel-Rawhide\x2dXfce\x2dLive\x2d715 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[  319.425427] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[  320.750729] audit: type=1130 audit(1437065492.903:15): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=dracut-initqueue comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[  320.778332] audit: type=1130 audit(1437065492.931:16): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=dracut-pre-mount comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[  320.840558] EXT4-fs (dm-0): mounted filesystem with ordered data mode. Opts: (null)


:/# 
````

**Comment by cinquecento** [comment]
```
/run/initramfs/rdsosreport.txt:
...
[    5.679088] localhost systemd[1]: Starting system-checkisomd5.slice.
[    5.679343] localhost systemd[1]: Starting Media check on /dev/disk/by-label/Rawhide-Xfce-Live-715...
[   91.987275] localhost systemd[1]: dev-mapper-live\x2drw.device: Job dev-mapper-live\x2drw.device/start timed out.
[   91.987572] localhost systemd[1]: Timed out waiting for device dev-mapper-live\x2drw.device.
[   91.988123] localhost systemd[1]: Dependency failed for /sysroot.
[   91.988470] localhost systemd[1]: Dependency failed for Initrd Root File System.
[   91.988859] localhost systemd[1]: Dependency failed for Reload Configuration from the Real Root.
[   91.989135] localhost systemd[1]: initrd-parse-etc.service: Job initrd-parse-etc.service/start failed with result 'dependency'.
[   91.989335] localhost systemd[1]: initrd-parse-etc.service: Triggering OnFailure= dependencies.
[   91.989747] localhost systemd[1]: initrd-root-fs.target: Job initrd-root-fs.target/start failed with result 'dependency'.
[   91.989942] localhost systemd[1]: initrd-root-fs.target: Triggering OnFailure= dependencies.
[   91.990230] localhost systemd[1]: sysroot.mount: Job sysroot.mount/start failed with result 'dependency'.
[   91.990439] localhost systemd[1]: dev-mapper-live\x2drw.device: Job dev-mapper-live\x2drw.device/start failed with result 'timeout'.
[   92.013677] localhost systemd[1]: Stopped dracut pre-pivot and cleanup hook.
[   92.014393] localhost systemd[1]: Stopped target Initrd Default Target.
[   92.014760] localhost systemd[1]: Stopped dracut mount hook.
[   92.015113] localhost systemd[1]: Stopped target Basic System.
[   92.015445] localhost systemd[1]: Stopping Basic System.
[   92.015693] localhost systemd[1]: Stopped target System Initialization.
[   92.016035] localhost systemd[1]: Stopping System Initialization.
[   92.040231] localhost systemd[1]: Starting Emergency Shell...
[   92.040458] localhost systemd[1]: Reached target Initrd File Systems.
[   92.040624] localhost systemd[1]: Starting Initrd File Systems.
[   92.060592] localhost kernel: audit_printk_skb: 3 callbacks suppressed
[   92.081556] localhost kernel: audit: type=1131 audit(1437065264.211:12): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=plymouth-start comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   92.086764] localhost systemd[1]: Received SIGRTMIN+21 from PID 400 (plymouthd).
[   92.086820] localhost audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=plymouth-start comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
:/# 
```

**Comment by cinquecento** [comment]
Of course, it's a physical media check, so the slow pace should be expected.

**Comment by gnurama** [comment]
I'm having the same timeout error:

[    3.225416] localhost systemd[1]: Started dracut initqueue hook.
[    3.225503] localhost systemd[1]: Reached target Remote File Systems (Pre).
[    3.225584] localhost systemd[1]: Starting Remote File Systems (Pre).
[    3.225665] localhost systemd[1]: Reached target Remote File Systems.
[    3.225744] localhost systemd[1]: Starting Remote File Systems.
[    3.225827] localhost systemd[1]: Started dracut pre-mount hook.
[    3.226060] localhost dracut-initqueue[269]: /lib/dracut-lib.sh@435(check_finished): for f in '$hookdir/initqueue/finished/*.sh'
[    3.226287] localhost dracut-initqueue[269]: /lib/dracut-lib.sh@436(check_finished): '[' '/lib/dracut/hooks/initqueue/finished/devexists-\x2fdev\x2fmapper\x2flive-rw.sh' = '/lib/dracut/hooks/initqueue/finished/*.sh' ']'
[    3.226537] localhost dracut-initqueue[269]: /lib/dracut-lib.sh@437(check_finished): '[' -e '/lib/dracut/hooks/initqueue/finished/devexists-\x2fdev\x2fmapper\x2flive-rw.sh' ']'
[    3.226770] localhost dracut-initqueue[269]: /lib/dracut-lib.sh@437(check_finished): . '/lib/dracut/hooks/initqueue/finished/devexists-\x2fdev\x2fmapper\x2flive-rw.sh'
[    3.226989] localhost dracut-initqueue[269]: //lib/dracut/hooks/initqueue/finished/devexists-\x2fdev\x2fmapper\x2flive-rw.sh@1(source): '[' -e /dev/mapper/live-rw ']'
[    3.227206] localhost dracut-initqueue[269]: /lib/dracut-lib.sh@439(check_finished): return 0
[    3.227414] localhost dracut-initqueue[269]: /bin/dracut-initqueue@45(main): break 2
[    3.227623] localhost dracut-initqueue[269]: /bin/dracut-initqueue@78(main): unset job
[    3.227848] localhost dracut-initqueue[269]: /bin/dracut-initqueue@79(main): unset queuetriggered
[    3.228062] localhost dracut-initqueue[269]: /bin/dracut-initqueue@80(main): unset main_loop
[    3.228273] localhost dracut-initqueue[269]: /bin/dracut-initqueue@81(main): unset RDRETRY
[    3.228482] localhost dracut-initqueue[269]: /bin/dracut-initqueue@83(main): export -p
[    3.228690] localhost dracut-initqueue[269]: /bin/dracut-initqueue@85(main): exit 0
[   18.349317] localhost kernel: random: nonblocking pool is initialized
[   91.056758] localhost systemd[1]: dev-mapper-live\x2drw.device: Job dev-mapper-live\x2drw.device/start timed out.
[   91.057014] localhost systemd[1]: Timed out waiting for device dev-mapper-live\x2drw.device.
[   91.057210] localhost systemd[1]: Dependency failed for /sysroot.
[   91.057404] localhost systemd[1]: Dependency failed for Initrd Root File System.
[   91.057600] localhost systemd[1]: Dependency failed for Reload Configuration from the Real Root.
[   91.057682] localhost systemd[1]: initrd-parse-etc.service: Job initrd-parse-etc.service/start failed with result 'dependency'.
[   91.057766] localhost systemd[1]: initrd-parse-etc.service: Triggering OnFailure= dependencies.
[   91.057846] localhost systemd[1]: initrd-root-fs.target: Job initrd-root-fs.target/start failed with result 'dependency'.
[   91.057926] localhost systemd[1]: initrd-root-fs.target: Triggering OnFailure= dependencies.
[   91.058003] localhost systemd[1]: sysroot.mount: Job sysroot.mount/start failed with result 'dependency'.
[   91.058081] localhost systemd[1]: dev-mapper-live\x2drw.device: Job dev-mapper-live\x2drw.device/start failed with result 'timeout'.

**Comment by gnurama** [comment]
If you're using fedora, did you by any chance install the dracut-live package?

**Comment by cinquecento** [comment]
We wouldn't write here, if we haven't already done that, right. ;)

**Comment by cinquecento** [comment]
```
$ du -hs /mnt/dvd | awk '{print $1}'
4.4G

$ time checkisomd5 /dev/sr0
Press [Esc] to abort check.

The media check is complete, the result is: PASS.

It is OK to use this media.

real	18m8.667s
...
```
18m8.667s ≈ 1089 seconds

For full single-sided / single-layer DVD,
Timeout[Start]Sec=1200 is probably sufficient value.

**Comment by cinquecento** [comment]
-OT-
gnurama, how do you compare these two tools:
- liveiso
  https://github.com/gnurama/liveiso
- livecd-creator
  https://github.com/rhinstaller/livecd-tools

**Comment by haraldh** [comment]
might be fixed with:
https://github.com/haraldh/dracut/commit/f4d64d55ea825ec0d05aaa76d58cddc37d44f719

**Comment by gnurama** [comment]
dracut-dmsquash-generator creates $GENERATOR_DIR/sysroot.mount and dracut-rootfs-generator doesn't touch it but systemd-fstab-generator does overwrite the sysroot.mount file which causes error like "Timed out waiting for device dev-mapper-live\x2drw.device." I don't know if it can be resolved by dracut or if systemd should skip writing sysroot.mount if it already exists.

I'm able to boot with rd.live.image by letting dracut-dmsquash-generator create sysroot.mount.new and then tell dracut-rootfs-generator to sysmlink sysroot.mount.new to initrd-root-fs.target.requires/sysroot.mount. Also I had to remove "if [ -z "$DRACUT_SYSTEMD" ]; then" condition from the dmsquash-live-root.sh in order to mount LiveOS/rootfs.img into /sysroot directory.

**Comment by cinquecento** [comment]
```
...
[    2.480146] random: nonblocking pool is initialized
[  OK  ] Started Show Plymouth Boot Screen.
[  OK  ] Reached target Paths.
[  OK  ] Reached target Basic System.
[  OK  ] Created slice system-checkisomd5.slice.
         Starting Media check on /dev/disk/by-label/Rawhide-Xfce-Live-718...
/dev/disk/by-label/Rawhide-Xfce-Live-718:   10b1f87b5aab70108a2fc29853d1c74c
Fragment sums: e323ab1f2f4983bd94762dadf7659edd6781f3d19c5f8c9aa6121dba292e
Fragment count: 20
Supported ISO: no
Press [Esc] to abort check.
Checking: 100.0%

The media check is complete, the result is: PASS.

It is OK to use this media.
[  OK  ] Started Media check on /dev/disk/by-label/Rawhide-Xfce-Live-718.
[  323.569208] ...
...
[  360.938574] ...

Fedora release 24 (Rawhide)
Kernel 4.2.0-0.rc2.git2.1.fc24.x86_64 on an x86_64 (ttyS0)

localhost login: 

```

**Comment by cinquecento** [comment]
Thanks.
